test_that("basic functionality", {
  expect_error(read_gpx('testdata/fake'))
  expect_equal(class(greasy_test <- read_gpx('testdata/greasy-creek-to-roan-high-knob.gpx')), "list")
  expect_length(greasy_test, 2)
  expect_length(greasy_test$tracks, 0)
  expect_length(greasy_test$routes, 1)
  expect_named(greasy_test, c('routes', 'tracks'))
  expect_equal(nrow(greasy_test$routes[[1]]), 563)
  expect_equal(ncol(greasy_test$routes[[1]]), 5)
  expect_true(all(is.na(greasy_test$routes[[1]][["extensions"]])))
  expect_true(all(is.na(greasy_test$routes[[1]][["Time"]])))
  expect_true(all(is.numeric(greasy_test$routes[[1]][["Elevation"]])))
  expect_true(all(is.numeric(greasy_test$routes[[1]][["Latitude"]])))
  expect_true(all(is.numeric(greasy_test$routes[[1]][["Longitude"]])))
})

test_that("cotswold", {
  expect_match(fn <- "cotswold-way", "*")
  expect_equal(class(test <- read_gpx(paste0('testdata/', fn ,'.gpx'))), "list")
  expect_equal(class(check_route <- read.csv(paste0('testdata/check/', fn ,'_route.csv'))), "data.frame")
  expect_equal(class(check_track <- read.csv(paste0('testdata/check/', fn ,'_track.csv'))), "data.frame")
  expect_equal(nrow(check_route), nrow(test$routes[[1]]))
  expect_equal(nrow(check_track), length(test$tracks))
  expect_true(all(test$routes[[1]]$Latitude == check_route$Latitude))
  expect_true(all(test$routes[[1]]$Longitude == check_route$Longitude))
  expect_true(all(test$routes[[1]]$Elevation == check_route$Elevation))
})

test_that("greasy", {
  expect_match(fn <- "greasy-creek-to-roan-high-knob", "*")
  expect_equal(class(test <- read_gpx(paste0('testdata/', fn ,'.gpx'))), "list")
  expect_equal(class(check_route <- read.csv(paste0('testdata/check/', fn ,'_route.csv'))), "data.frame")
  expect_equal(class(check_track <- read.csv(paste0('testdata/check/', fn ,'_track.csv'))), "data.frame")
  expect_equal(nrow(check_route), nrow(test$routes[[1]]))
  expect_equal(nrow(check_track), length(test$tracks))
  expect_true(all(test$routes[[1]]$Latitude == check_route$Latitude))
  expect_true(all(test$routes[[1]]$Longitude == check_route$Longitude))
  expect_true(all(test$routes[[1]]$Elevation == check_route$Elevation))
})

test_that("bayes", {
  expect_match(fn <- "Bayes_Mountain_Fire_Tower_TN", "*")
  expect_equal(class(test <- read_gpx(paste0('testdata/', fn ,'.gpx'))), "list")
  expect_equal(class(check_route <- read.csv(paste0('testdata/check/', fn ,'_route.csv'))), "data.frame")
  expect_equal(class(check_track <- read.csv(paste0('testdata/check/', fn ,'_track.csv'))), "data.frame")
  expect_equal(nrow(check_route), length(test$routes))
  expect_equal(nrow(check_track), nrow(test$tracks[[1]]))
  expect_true(all(test$tracks[[1]]$Latitude == check_track$Latitude))
  expect_true(all(test$tracks[[1]]$Longitude == check_track$Longitude))
  expect_true(all(test$tracks[[1]]$Elevation == check_track$Elevation))
})

test_that("beauty spot", {
  expect_match(fn <- "Beauty_Spot_TN", "*")
  expect_equal(class(test <- read_gpx(paste0('testdata/', fn ,'.gpx'))), "list")
  expect_equal(class(check_route <- read.csv(paste0('testdata/check/', fn ,'_route.csv'))), "data.frame")
  expect_equal(class(check_track <- read.csv(paste0('testdata/check/', fn ,'_track.csv'))), "data.frame")
  expect_equal(nrow(check_route), length(test$routes))
  expect_equal(nrow(check_track), nrow(test$tracks[[1]]))
  expect_true(all(test$tracks[[1]]$Latitude == check_track$Latitude))
  expect_true(all(test$tracks[[1]]$Longitude == check_track$Longitude))
  expect_true(all(test$tracks[[1]]$Elevation == check_track$Elevation))
})

test_that("boone fork", {
  expect_match(fn <- "Boone_Fork_Loop_NC", "*")
  expect_equal(class(test <- read_gpx(paste0('testdata/', fn ,'.gpx'))), "list")
  expect_equal(class(check_route <- read.csv(paste0('testdata/check/', fn ,'_route.csv'))), "data.frame")
  expect_equal(class(check_track <- read.csv(paste0('testdata/check/', fn ,'_track.csv'))), "data.frame")
  expect_equal(nrow(check_route), length(test$routes))
  expect_equal(nrow(check_track), nrow(test$tracks[[1]]))
  expect_true(all(test$tracks[[1]]$Latitude == check_track$Latitude))
  expect_true(all(test$tracks[[1]]$Longitude == check_track$Longitude))
  expect_true(all(test$tracks[[1]]$Elevation == check_track$Elevation))
})

test_that("cranberry lake", {
  expect_match(fn <- "Cranberry_Lake_NY", "*")
  expect_equal(class(test <- read_gpx(paste0('testdata/', fn ,'.gpx'))), "list")
  expect_equal(class(check_route <- read.csv(paste0('testdata/check/', fn ,'_route.csv'))), "data.frame")
  expect_equal(class(check_track <- read.csv(paste0('testdata/check/', fn ,'_track.csv'))), "data.frame")
  expect_equal(nrow(check_route), length(test$routes))
  expect_equal(nrow(check_track), nrow(test$tracks[[1]]))
  expect_true(all(test$tracks[[1]]$Latitude == check_track$Latitude))
  expect_true(all(test$tracks[[1]]$Longitude == check_track$Longitude))
  expect_true(all(test$tracks[[1]]$Elevation == check_track$Elevation))
})

test_that("laurel run", {
  expect_match(fn <- "Laurel_Run_Falls_TN", "*")
  expect_equal(class(test <- read_gpx(paste0('testdata/', fn ,'.gpx'))), "list")
  expect_equal(class(check_route <- read.csv(paste0('testdata/check/', fn ,'_route.csv'))), "data.frame")
  expect_equal(class(check_track <- read.csv(paste0('testdata/check/', fn ,'_track.csv'))), "data.frame")
  expect_equal(nrow(check_route), length(test$routes))
  expect_equal(nrow(check_track), nrow(test$tracks[[1]]))
  expect_true(all(test$tracks[[1]]$Latitude == check_track$Latitude))
  expect_true(all(test$tracks[[1]]$Longitude == check_track$Longitude))
  expect_true(all(test$tracks[[1]]$Elevation == check_track$Elevation))
})

test_that("palmetto", {
  expect_match(fn <- "Palmetto_Trail_SC", "*")
  expect_equal(class(test <- read_gpx(paste0('testdata/', fn ,'.gpx'))), "list")
  expect_equal(class(check_route <- read.csv(paste0('testdata/check/', fn ,'_route.csv'))), "data.frame")
  expect_equal(class(check_track <- read.csv(paste0('testdata/check/', fn ,'_track.csv'))), "data.frame")
  expect_equal(nrow(check_route), length(test$routes))
  expect_equal(nrow(check_track), nrow(test$tracks[[1]]))
  expect_true(all(test$tracks[[1]]$Latitude == check_track$Latitude))
  expect_true(all(test$tracks[[1]]$Longitude == check_track$Longitude))
  expect_true(all(test$tracks[[1]]$Elevation == check_track$Elevation))
})

test_that("salins", {
  expect_match(fn <- "Salins-les-Bains", "*")
  expect_equal(class(test <- read_gpx(paste0('testdata/', fn ,'.gpx'))), "list")
  expect_equal(class(check_route <- read.csv(paste0('testdata/check/', fn ,'_route.csv'))), "data.frame")
  expect_equal(class(check_track <- read.csv(paste0('testdata/check/', fn ,'_track.csv'))), "data.frame")
  expect_equal(nrow(check_route), length(test$routes))
  expect_equal(nrow(check_track), nrow(test$tracks[[1]]))
  expect_true(all(test$tracks[[1]]$Latitude == check_track$Latitude))
  expect_true(all(test$tracks[[1]]$Longitude == check_track$Longitude))
  expect_true(all(test$tracks[[1]]$Elevation == check_track$Elevation))
})
